name: Repository Structure Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-structure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check repository structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "-------------------------------"
        
        echo "Checking for wizard-coding-academy folder:"
        if [ -d "wizard-coding-academy" ]; then
          echo "Folder exists! Contents:"
          ls -la wizard-coding-academy
        else
          echo "Folder does not exist in the repository."
        fi